#!/bin/bash
blue='\033[1;34m'
red='\033[1;31m'
nc='\033[0m'
lc='\033[1;36m'

# This is because MacOs doesn't have this function.
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

echo -e "${blue}> Install client packages? (y/n)"
read yn
case $yn in
    [Yy]* )

        cd ./client
        echo -e "> ${lc}Installing node modules...${nc}"
        npm install
        cd ..

    ;;
esac

echo -e "${blue}> Install server packages? (y/n)"
read yn
case $yn in
    [Yy]* )

        cd ./server
        echo -e "> ${lc}Installing node modules...${nc}"
        npm install
        cd ..

    ;;
esac